apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: macvlan-conf
plugin: macvlan
args: '[
        {          
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.122.0/24",
            "rangeStart": "192.168.122.200",
            "rangeEnd": "192.168.122.216",
            "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "gateway": "192.168.122.1"
         }
        }
]'
