apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iptables-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: iptables
    spec:
      containers:
      - name: iptables
        image: ubuntu:16.04
