apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iptable-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: iptables
    spec:
      containers:
        - name: iptables
          image: vimagick/iptables:latest
          command: ["/bin/sh"]
          args: ["/etc/iptables/rules.sh"]
          volumeMounts:
          - name: iptables-cfg
            mountPath: /etc/iptables/
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN                
          env:
          - name: TCP_PORTS
            value: "80,443"
          - name: UDP_PORTS
            value: "53"
          - name: RATE
            value: "4mbit"
          - name: BURST
            value: "4kb"
        volumes:
          - name: iptables-cfg
            configMap:
              name: iptables-cfg
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: iptables-cfg
  labels:
    name: iptables
data:
  rules.sh: |
    iptables -F
    iptables -t nat -A PREROUTING -i eth0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.122.202
    iptables -t nat -A POSTROUTING -o net0 -p tcp -m tcp --dport 80 -j SNAT --to-source 192.168.122.200
---
