
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iptable-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: iptables
    spec:
      containers:
        - name: iptables
          image: vimagick/iptables:latest
          port:
          - containerPort: 80
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN                
          env:
          - name: TCP_PORTS
            value: "80,443"
          - name: UDP_PORTS
            value: "53"
          - name: RATE
            value: "4mbit"
          - name: BURST
            value: "4kb"
