apiVersion: v1
kind: Pod
metadata:
  name: iptables-pod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: iptables
    spec:
      containers:
      - name: iptables
        image: vimagick/iptables:latest
