kind: Service
apiVersion: v1
metadata:
  name: iptables-service
  labels:
    app: iptables
spec:
  type: NodePort
  selector:
    app: iptables
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
