apiVersion: v1
kind: Service
metadata:
  name: iptables-service
  labels:
    name: iptables
spec:
  type: NodePort
  selector:
    name: iptables
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
